Mostly finished project_setup script

diff --git a/project_setup b/project_setup
--- a/project_setup
+++ b/project_setup
@@ -6,7 +6,8 @@
 # 1: No/Wrong arguments specified
 # 2: Script was not run as root
 # 3: "No" was specified when prompted to continue with install/removal
-# Last modified on 24 Nov 2014
+# 4: Uninstall failed because it could not find /etc/myproject_config
+# Last modified on 26 Nov 2014
 
 # Useful variables:
 # confirmed (bool): Created by the confirm function and says whether the user decided to continue from the last prompt. (answered yes=true)
@@ -86,6 +87,16 @@ function prompt_for_folder() {
     done
 }
 
+# Deletes the backup of the specified file
+# Syntax: delete_backup_file [config file...]
+function delete_backup_file() {
+    # The for loop takes wildcards into account
+    for next_file in $@
+    do
+        rm "$backup_directory/$(basename $next_file)"
+    done
+}
+
 # Show usage info if no argument is specified
 if [ -z $@ ]
 then
@@ -126,6 +137,24 @@ then
         # Move the config file to /etc/myproject_config (this location cannot be changed)
         # Make sure to change the permissions of the backup dir and the key file
         
+        # Create the config file
+        echo "email=$email" >> /etc/myproject_config
+        echo "install_directory=$install_directory" >> /etc/myproject_config
+        echo "checksum_directory=$checksum_directory" >> /etc/myproject_config
+        echo "backup_directory=$backup_directory" >> /etc/myproject_config
+        echo "scan_freq=$scan_freq" >> /etc/myproject_config
+        # Move the executables to the specified directory
+        cp ./create_sums "$install_directory/create_sums"
+        cp ./sum_test "$install_directory/create_sums"
+        # Move the service file to the correct directory
+        cp ./bash_file_monitor.service /etc/systemd/system/bash_file_monitor.service
+        # Move the file list to the checksum directory
+        cp ./filelist.txt "$checksum_directory/filelist.txt"
+        # Create the checksum and backup directories if they don't exist. Also set their permissions.
+        mkdir $checksum_directory > /dev/null
+        mkdir $backup_directory > /dev/null
+        chmod 600 $checksum_directory
+        chmod 600 $backup_directory
     else
         # User did not go through with install
         exit 3
@@ -143,6 +172,30 @@ then
         echo "Removing..."
          # ADD ALL THIS AS WELL
          # Notes: check if the /var/lib/ntwk2001/* (or alt) directory is empty once all files are gone. If so, delete the folder.
+         # Check if the config exists. If so, import it.
+         if [ -e /etc/myproject_config ]
+         then
+            /etc/myproject_config
+            echo "Removing checksums..."
+            rm "$checksum_directory/checksums.conf"
+            echo "Removing backups..."
+            for NEXT in `cat "$checksum_directory/filelist.txt"`
+            do
+                delete_backup_file "$NEXT"
+            done
+            echo "Removing file list..."
+            rm "$checksum_directory/filelist.txt"
+            echo "Removing executables..."
+            rm "$install_directory/create_sums"
+            rm "$install_directory/sum_test"
+            echo "Remove systemd script..."
+            rm "/etc/systemd/system/bash_file_monitor.service"
+            echo "Removing config..."
+            rm "/etc/myproject_config"
+            echo -e "\nDone!"
+         else
+            echo "Installed config does not exist. Uninstall failed."
+            exit 4
     else
         # User did not go through with uninstall
         exit 3
